ENTITY_SCHEMAS: dict[str, dict] = {
    "account": {
        "label": "客户",
        "api_key": "account",
        "items": [
            {"api_key": "accountChannel", "label": "来源方式", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar20"},
            {"api_key": "accountName", "label": "客户名称", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "name"},
            {"api_key": "accountScore", "label": "客户得分", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 6, "db_column": "dbc_decimal6"},
            {"api_key": "actualInvoicedAmount", "label": "实际应收账金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint24"},
            {"api_key": "amountUnbilled", "label": "未出应收账金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint28"},
            {"api_key": "annualRevenue", "label": "销售额", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 6, "db_column": "dbc_decimal3"},
            {"api_key": "claimTime", "label": "认领日期", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint11"},
            {"api_key": "duplicateFlg", "label": "疑似查重", "item_type": "BOOLEAN", "paas_item_type": 31, "paas_data_type": 31, "db_column": "dbc_smallint3"},
            {"api_key": "employeeNumber", "label": "总人数", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint4"},
            {"api_key": "expireTime", "label": "到期时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint13"},
            {"api_key": "fCity", "label": "市", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar17"},
            {"api_key": "fDistrict", "label": "区", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar18"},
            {"api_key": "fState", "label": "省份", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar16"},
            {"api_key": "highSeaAccountSource", "label": "客户来源", "item_type": "PICK_LIST", "paas_item_type": 3, "paas_data_type": 3, "db_column": "dbc_varchar12"},
            {"api_key": "highSeaId", "label": "所属公海", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 5, "db_column": "dbc_bigint8", "refer_entity": "highSea"},
            {"api_key": "highSeaStatus", "label": "状态", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar21"},
            {"api_key": "industryId", "label": "行业", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar15"},
            {"api_key": "invoiceBalance", "label": "应收余额（欠款）", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint29"},
            {"api_key": "isCustomer", "label": "是否为结单客户", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 1, "db_column": "dbc_varchar2"},
            {"api_key": "paidAmount", "label": "实际收款金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint30"},
            {"api_key": "parentAccountId", "label": "上级客户", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint3", "refer_entity": "account"},
            {"api_key": "paymentHealthPct", "label": "应收健康度", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 0, "db_column": "dbc_decimal8"},
            {"api_key": "paymentRate", "label": "账户支付比例", "item_type": "DECIMAL", "paas_item_type": 33, "paas_data_type": 33, "db_column": "dbc_decimal4"},
            {"api_key": "recentActivityCreatedBy", "label": "最新跟进人", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint6", "refer_entity": "user"},
            {"api_key": "releaseDescription", "label": "退回公海描述", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar13"},
            {"api_key": "score", "label": "客户分值", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint19"},
            {"api_key": "territoryHighSeaId", "label": "所属区域公海", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint27", "refer_entity": "territory"},
            {"api_key": "totalActiveOrders", "label": "生效订单数", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint32"},
            {"api_key": "totalContract", "label": "合同数", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint34"},
            {"api_key": "totalOrderAmount", "label": "订单总金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint33"},
            {"api_key": "totalWonOpportunities", "label": "结单商机数", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint23"},
            {"api_key": "totalWonOpportunityAmount", "label": "结单商机总金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint31"},
            {"api_key": "unpaidAmount", "label": "未收款金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 6, "db_column": "dbc_decimal5"},
            {"api_key": "valueScore", "label": "客户价值评分", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 0, "db_column": "dbc_decimal7"},
            {"api_key": "vipFlag", "label": "VIP标识", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_varchar14"},
            {"api_key": "visitLatestTime", "label": "最近拜访时间", "item_type": "DATETIME", "paas_item_type": 38, "paas_data_type": 38, "db_column": "dbc_bigint21"},
            {"api_key": "visitTotalCount", "label": "拜访总数", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5, "db_column": "dbc_bigint36"},
            {"api_key": "visitUnvisitDay", "label": "未拜访天数", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint22"},
        ],
        "links": [
            {"target": "{}", "type": "MANY_TO_ONE", "label": "客户"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "订单"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "合同"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "销售机会"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "销售线索"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "应收单"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "报价单"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "联系人"},
        ],
    },
    "contact": {
        "label": "联系人",
        "api_key": "contact",
        "items": [
            {"api_key": "address", "label": "地址", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar8"},
            {"api_key": "comment", "label": "备注", "item_type": "TEXT", "paas_item_type": 4, "paas_data_type": 4, "db_column": "dbc_textarea1"},
            {"api_key": "contactBirthday", "label": "出生日期", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint4"},
            {"api_key": "contactChannel", "label": "来源方式", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int3"},
            {"api_key": "contactName", "label": "姓名", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "name"},
            {"api_key": "contactRole", "label": "联系人角色", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int6"},
            {"api_key": "contactScore", "label": "联系人得分", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 6},
            {"api_key": "countryId", "label": "城市", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint17"},
            {"api_key": "depart", "label": "部门", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar2"},
            {"api_key": "doNotDisturb", "label": "免打扰", "item_type": "BOOLEAN", "paas_item_type": 31, "paas_data_type": 31, "db_column": "dbc_smallint1"},
            {"api_key": "email", "label": "电子邮件", "item_type": "VARCHAR", "paas_item_type": 23, "paas_data_type": 23, "db_column": "email"},
            {"api_key": "externalUserId", "label": "扩展用户", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint19"},
            {"api_key": "gender", "label": "性别", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int1"},
            {"api_key": "leadId", "label": "线索", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint13"},
            {"api_key": "mobile", "label": "手机", "item_type": "VARCHAR", "paas_item_type": 22, "paas_data_type": 22, "db_column": "dbc_varchar5"},
            {"api_key": "phone", "label": "电话", "item_type": "VARCHAR", "paas_item_type": 22, "paas_data_type": 22, "db_column": "dbc_varchar4"},
            {"api_key": "pinyin", "label": "拼音", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar11"},
            {"api_key": "post", "label": "职务", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar3"},
            {"api_key": "recentActivityRecordId", "label": "最新活动记录", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint20", "refer_entity": "activityrecord"},
            {"api_key": "recentActivityRecordTime", "label": "最新活动记录时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint5"},
            {"api_key": "recentActivityRecordType", "label": "最新活动记录类型", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint21"},
            {"api_key": "registrationUtmId", "label": "关联UTM", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint29", "refer_entity": "592"},
            {"api_key": "state", "label": "省份", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar7"},
            {"api_key": "territoryId", "label": "区域", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "territory_id", "refer_entity": "territory"},
            {"api_key": "zipCode", "label": "邮政编码", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar9"},
        ],
        "links": [
            {"target": "{}", "type": "MANY_TO_ONE", "label": "销售机会"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "销售线索"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "订单"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "报价单"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "应收单"},
        ],
    },
    "opportunity": {
        "label": "商机",
        "api_key": "opportunity",
        "items": [
            {"api_key": "actualCost", "label": "实际花费", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 6, "db_column": "dbc_decimal3"},
            {"api_key": "actualPeriod", "label": "实际周期", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint24"},
            {"api_key": "campaignContactId", "label": "联系人", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint18", "refer_entity": "contact"},
            {"api_key": "campaignId", "label": "市场活动", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint19", "refer_entity": "campaign"},
            {"api_key": "closeDate", "label": "结单日期", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint8"},
            {"api_key": "commitmentFlg", "label": "承诺", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int3"},
            {"api_key": "discount", "label": "折扣", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 6, "db_column": "dbc_decimal4"},
            {"api_key": "duplicateCheckExplanation", "label": "查重结果说明", "item_type": "TEXT", "paas_item_type": 4, "paas_data_type": 4, "db_column": "dbc_textarea4"},
            {"api_key": "duplicateCheckResultTime", "label": "智能查重时间", "item_type": "DATETIME", "paas_item_type": 38, "paas_data_type": 38, "db_column": "dbc_bigint32"},
            {"api_key": "fcastMoney", "label": "预测金额", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 6},
            {"api_key": "forecastCategory", "label": "阶段分类", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int7"},
            {"api_key": "intelligentDuplicateCheckResult", "label": "智能查重结果", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar7"},
            {"api_key": "invoiceDate", "label": "开票日期", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint22"},
            {"api_key": "lostStageId", "label": "输单阶段", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint5", "refer_entity": "-10500"},
            {"api_key": "money", "label": "销售金额", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 6, "db_column": "dbc_decimal1"},
            {"api_key": "oppHealthAssessmentLevel", "label": "商机健康度等级", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int9"},
            {"api_key": "oppHealthAssessmentScore", "label": "商机评分", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 6, "db_column": "dbc_decimal5"},
            {"api_key": "oppHealthAssessmentShow", "label": "商机健康度等级展示", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar8"},
            {"api_key": "opportunityCode", "label": "机会编号", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar5"},
            {"api_key": "opportunityName", "label": "机会名称", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "name"},
            {"api_key": "opportunityScore", "label": "商机得分", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 6},
            {"api_key": "opportunityType", "label": "机会类型", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int1"},
            {"api_key": "paymentDate", "label": "付款日期", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint23"},
            {"api_key": "priceId", "label": "价格表名称", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint3", "refer_entity": "priceBook"},
            {"api_key": "projectBudget", "label": "项目预算", "item_type": "DECIMAL", "paas_item_type": 6, "paas_data_type": 6, "db_column": "dbc_decimal2"},
            {"api_key": "reasonDesc", "label": "输单描述", "item_type": "TEXT", "paas_item_type": 4, "paas_data_type": 4, "db_column": "dbc_textarea1"},
            {"api_key": "repeatFlg", "label": "重复标志", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint20"},
            {"api_key": "roiCiCount", "label": "ROI影响力计数", "item_type": "DECIMAL", "paas_item_type": 27, "paas_data_type": 5},
            {"api_key": "saleStageId", "label": "销售阶段", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint6", "refer_entity": "-10500"},
            {"api_key": "seemDuplicateRuleId", "label": "疑似查重规则id", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint33"},
            {"api_key": "sourceId", "label": "机会来源", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint9"},
            {"api_key": "stageUpdatedAt", "label": "阶段更新时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint11"},
            {"api_key": "standardPeriod", "label": "标准周期", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint21"},
            {"api_key": "suspectedOpportunityAnalysis", "label": "疑似商机分析", "item_type": "TEXT", "paas_item_type": 4, "paas_data_type": 4, "db_column": "dbc_textarea5"},
            {"api_key": "winRate", "label": "赢率", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint7"},
            {"api_key": "winReason", "label": "赢单原因", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int8"},
            {"api_key": "winReasonDesc", "label": "赢单描述", "item_type": "TEXT", "paas_item_type": 4, "paas_data_type": 4, "db_column": "dbc_textarea3"},
        ],
        "links": [
            {"target": "{}", "type": "MANY_TO_ONE", "label": "销售线索"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "合同"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "订单"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "报价单"},
        ],
    },
    "lead": {
        "label": "线索",
        "api_key": "lead",
        "items": [
            {"api_key": "adDmpLeadId", "label": "广告线索id", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar17"},
            {"api_key": "adPlanName", "label": "广告计划名称", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar18"},
            {"api_key": "adPlatform", "label": "广告投放平台", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar19"},
            {"api_key": "adProjectName", "label": "项目名称", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar21"},
            {"api_key": "adRetentionTime", "label": "广告留资时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint35"},
            {"api_key": "adSource", "label": "广告投放来源", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar20"},
            {"api_key": "applyDelayTime", "label": "延期时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint26"},
            {"api_key": "bdType", "label": "大数据类型", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int11"},
            {"api_key": "claimTime", "label": "认领日期", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 3, "db_column": "dbc_bigint6"},
            {"api_key": "companyName", "label": "公司名称", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar2"},
            {"api_key": "contactId", "label": "联系人", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint27", "refer_entity": "contact"},
            {"api_key": "countryId ", "label": "省份", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar13"},
            {"api_key": "expireTime", "label": "到期时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 3, "db_column": "dbc_bigint7"},
            {"api_key": "lastOwnerId", "label": "最后所有人", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint33", "refer_entity": "user"},
            {"api_key": "leadChannel", "label": "来源方式", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int7"},
            {"api_key": "leadHighSeaId", "label": "所属线索公海", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 3, "db_column": "dbc_bigint5", "refer_entity": "leadHighSea"},
            {"api_key": "leadHighSeaStatus", "label": "公海状态", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 1, "db_column": "dbc_varchar9"},
            {"api_key": "leadQuality", "label": "线索质量", "item_type": "PICK_LIST", "paas_item_type": 2, "paas_data_type": 2, "db_column": "dbc_int10"},
            {"api_key": "leadScore", "label": "线索得分", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint18"},
            {"api_key": "leadSourceId", "label": "线索来源", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint4"},
            {"api_key": "opportunityId", "label": "销售机会", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 10, "db_column": "dbc_bigint22", "refer_entity": "opportunity"},
            {"api_key": "phoneLocation", "label": "手机号归属地", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar23"},
            {"api_key": "releaseDefinition", "label": "退回原因说明", "item_type": "VARCHAR", "paas_item_type": 1, "paas_data_type": 1, "db_column": "dbc_varchar15"},
            {"api_key": "releaseNum", "label": "退回公海次数", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint29"},
            {"api_key": "releaseReason", "label": "退回原因", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint31"},
            {"api_key": "releaseTime", "label": "退回时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint32"},
            {"api_key": "returnTimes", "label": "退回次数", "item_type": "INTEGER", "paas_item_type": 5, "paas_data_type": 5, "db_column": "dbc_bigint34"},
            {"api_key": "scoreDetail", "label": "线索得分分析", "item_type": "TEXT", "paas_item_type": 4, "paas_data_type": 4, "db_column": "dbc_textarea2"},
            {"api_key": "statusUpdatedAt", "label": "状态更新时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint23"},
            {"api_key": "territoryLeadHighSeaId", "label": "所属区域线索公海", "item_type": "RELATIONSHIP", "paas_item_type": 10, "paas_data_type": 3, "db_column": "dbc_bigint16", "refer_entity": "territory"},
            {"api_key": "thawTime", "label": "解冻时间", "item_type": "DATE", "paas_item_type": 7, "paas_data_type": 7, "db_column": "dbc_bigint30"},
        ],
        "links": [
            {"target": "leadHighSea", "type": "MANY_TO_ONE", "label": "公海线索"},
            {"target": "territory", "type": "MANY_TO_ONE", "label": "区域线索公海"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "客户"},
            {"target": "{}", "type": "MANY_TO_ONE", "label": "销售机会"},
        ],
    },
}